<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<LangVersion>latest</LangVersion>
	<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	<BaseOutputPath>C:\Users\Topaz\Documents\Projects\ReFined\Build\Kingdom Hearts II</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\prologue_flags.byte" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\prologue_flags.byte" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Third Party\BinarySharp\BinarySharp.csproj" />
    <ProjectReference Include="..\..\Third Party\DiscordRPC\DiscordRPC.csproj" />
    <ProjectReference Include="..\..\Third Party\KH2-FML\KH2-FML.csproj" />
  </ItemGroup>

</Project>
