# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Kingdom Hearts II - Build and Sync

on:
  push:
    paths:
      - "ReFined.KH2/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "ReFined.KH2/**"
      - ".github/workflows/**" 
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ReFined.sln
  CONFIG_BUILD: Release
  PLATFORM_BUILD: x64

permissions:
  contents: write

jobs:
  build-kh2:
    runs-on: windows-latest

    steps:
    - name: Fetch Repo - KH-ReFined
      uses: actions/checkout@v5
      with:
        path: 'src'
        ref: 'mother'
        repository: 'KH-ReFined/KH-ReFined'
        persist-credentials: false
        
    - uses: microsoft/setup-msbuild@v3
    
    - name: Build - ReFined.KH2.dll
      working-directory: "src/"
      run: msbuild /m /p:Configuration=${{env.CONFIG_BUILD}} /p:Platform=${{env.PLATFORM_BUILD}} ${{env.SOLUTION_FILE_PATH}}

    - name: Fetch Repo - KH2-MAIN
      uses: actions/checkout@v5
      with:
        path: 'dest'
        ref: 'main'
        repository: 'KH-ReFined/KH2-MAIN'
        token: ${{ secrets.KH2_PUSHKEY }}
        fetch-depth: 0
        persist-credentials: false
        
    - name: Synchronize Output to KH2-MAIN
      run: | 
        Copy-Item -Path "src/x64/Release/ReFined.KH2.dll" -Destination "dest/engine/"
        Copy-Item -Path "src/x64/Release/ModuleRF-*.dll" -Destination "dest/engine/modules"

    - name: Edit Build Number within KH2-MAIN/mod.yml
      run: |
        $fetchyaml = Get-Content "dest/mod.yml"
        $fetchyaml[2] = "description: Kingdom Hearts - Re:Fined for Kingdom Hearts II | r$(Get-Date -Format 'ddMMyy-HHmm')-FC"
        $fetchyaml | Set-Content "dest/mod.yml"

    - name: Edit Build Number within KH-ReFined/ReadME.md
      run: |
        $fetchreadme = Get-Content "src/ReadME.md"
        $fetchreadme[10] = "![KHII](https://img.shields.io/badge/Kingdom_Hearts_II-r$(Get-Date -Format 'ddMMyy--HHmm')--FC-dark_lime)"
        $fetchreadme | Set-Content "src/ReadME.md"

    - name: Push ReadME to KH-ReFined
      run: |
        cd src
                
        git config user.name "Kingdom Hearts - Re:Fined"
        git config user.email "github@kh-refined.dev"
        git remote set-url origin https://KH-ReFined:${{secrets.KH2_PUSHKEY}}@github.com/KH-ReFined/KH-ReFined.git

        git add .
        git commit -m "Synchronize from KH-ReFined [BOT] - Push Date: $(Get-Date -Format 'dd/MM/yy')"
        git push origin mother

    - name: Push to KH2-MAIN
      run: |
        cd dest
        
        git config user.name "Kingdom Hearts - Re:Fined"
        git config user.email "github@kh-refined.dev"
        git remote set-url origin https://KH-ReFined:${{secrets.KH2_PUSHKEY}}@github.com/KH-ReFined/KH2-MAIN.git

        git add .
        git commit -m "Synchronize from KH-ReFined [BOT] - Push Date: $(Get-Date -Format 'dd/MM/yy')"
        git push origin main
